### ISSUE TITLE
CUDA out of memory despite having a lot of free GPU memory

### ISSUE THREAD

**Issue by Mh-Magdy** [EnVision-Research/Lotus#10]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.37 GiB. GPU .
The GPU memory is totally free and i still get this error each run?!

**Comment by BlingHe** [comment]
What is the resolution of your images? And how about the total GPU memory of your device?

**Comment by Mh-Magdy** [comment]
Test Image Resolution:  612x408
My GPU memory: 6144MiB

**Comment by BlingHe** [comment]
A little bit odd (⊙_⊙). I tried an image with a resolution of 685x609, but it only required 2947MiB of memory. 
Have you enabled half precision?

**Comment by Mh-Magdy** [comment]
I got the same error even with the infer.sh script on the example images with half precision enabled by default inside infer.sh.

![image](https://github.com/user-attachments/assets/cd9cd840-f58b-4f3a-9072-4c02db7a3d29)

I tested Lotus on google colab [T4 gpu] and ran the infer.sh script and got the same error.

![image](https://github.com/user-attachments/assets/38b630cf-a24f-45ab-84e1-93e0d9cab125)

**Comment by BlingHe** [comment]
Thanks for pointing out the problem, let me check the code.

**Comment by BlingHe** [comment]
Hi, you can add `torch.cuda.empty_cache()` after each inference. Please refer to [this line](https://github.com/EnVision-Research/Lotus/blob/main/infer.py#L185).

**Comment by Mh-Magdy** [comment]
Thank you for your prompt response. I'll try the fix and let you know the update.
Thank once again for your great work.

**Comment by haodong2000** [comment]
Issue closed, please re-open it upon any problems :hugs:
