### ISSUE TITLE
how to get metric depth?

### ISSUE THREAD

**Issue by Vincent630** [EnVision-Research/Lotus#13]
Hi, does this work can predict metric depth ? i found infer.sh result is not metric depth,so o wonder if this work can get metric depth and if it can ,how to get it？ thank  a lot

**Comment by BlingHe** [comment]
Thanks for your notice!

Our model predicts affine-invariant depth maps, similar to Marigold, without the scale and shift factors to convert them to metric depth. If you need metric depth, you can align our predictions with other information, such as lidar measurements or metric depth from other methods. After alignment, you can apply the obtained scale and shift factors to convert our predictions to metric depth. You can refer to [this snippest](https://github.com/EnVision-Research/Lotus/blob/main/evaluation/evaluation.py#L213) for more details on the alignment process. 

Best,

**Comment by Vincent630** [comment]
i have test depth pro,it seem can not predict the right metric depth when i offer some custome&nbsp; picture

---Original---
From: "John D. ***@***.***&gt;
Date: Fri, Oct 11, 2024 21:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EnVision-Research/Lotus] how to get metric depth? (Issue #13)




 
breaking update
 https://github.com/apple/ml-depth-pro
