### ISSUE TITLE
Hello,  thank you for your excellent work. Please allow me to seek a bit of assistance.

### ISSUE THREAD

**Issue by ckh0715** [EnVision-Research/Lotus#14]
Could your provided code output the specific normal values and correctly transform them based on the camera parameters? I believe your work could potentially benefit some downstream tasks.

**Comment by haodong2000** [comment]
Hi there, thanks so much for your interest!

However I am a little confused about your question. The normal maps you see are directly saved from the network output: https://github.com/EnVision-Research/Lotus/blob/1650b6386930a57d080544017210f408a35f2e58/infer.py#L179-L180
, without any camera parameters.

What's your "correctly transform them based on the camera parameters" meaning? Lifting the normal map into 3D point clouds and then applying transformation?

Best,

**Comment by haodong2000** [comment]
Hi there,

I've tried to project the predicted depth map into 3D with camera parameters (mainly intrinsics), and it seems quite well. Here are the teaser's 3D view:

https://github.com/user-attachments/assets/7ad8de1b-fe50-4c15-8d11-9cbb6f5c4895

https://github.com/user-attachments/assets/694f05f5-09b3-4ff2-b600-dfcb684ba199

For normal maps, the model should predict the relative normal directions, thus, I believe that it can be transformed into world coordinates given the camera parameters (mainly extrinsics?). Here is a toy example with flipped input to demonstrate that the model predicts relative normal maps.

![image](https://github.com/user-attachments/assets/b074748e-bdd5-4876-b269-9155a147bd5c)

![image](https://github.com/user-attachments/assets/31259597-b172-4ca9-b56b-a9e258e12f9b)

Thanks again for your attention!
