### ISSUE TITLE
What is the difference between the 'generation' and the 'regression' models?

### ISSUE THREAD

**Issue by rafaelspring** [EnVision-Research/Lotus#18]
Which one would I use for regular inference (image in, depth or normals out)?

**Comment by haodong2000** [comment]
Hi @rafaelspring , thanks for your interest!

For regular inference you said, please use `regression` mode.

The difference is simple: in `generation` mode, the RGB image serves as a condition, and the dense annotations are **generated** from Gaussian noise in one step (which enables distribution modelling). In `regression` mode, we remove the noise input, and directly predicts dense labels from the RGB image.

Shortly, in `generation` mode, the inputs are RGB image and Gaussian noise. In `regression`, the input is only the RGB image.

Best,
