### ISSUE TITLE
Is it possible to get more shots from various angles ?

### ISSUE THREAD

**Issue by altava-sgp** [EnVision-Research/Lotus#19]
At first thanks for your great job! 👍 

I have a question.
Is it possible to get more shots from various angles ?
A only single shot is possible ?

Please excuse me if I am missing anything.

**Comment by haodong2000** [comment]
Hi @altava-sgp thanks so much for your interest! Sorry for my late response.

Do you mean to get multi views of depth and normal given a single RGB image?

For depth estimation: you can lift the depth maps into 3D point clouds using camera intrinsics and then render new depth maps or RGB from different views. As shown in [this issue](https://github.com/EnVision-Research/Lotus/issues/14#issuecomment-2409094495).

For normal, if you want mulri views of normal maps, you probably should do: normal -> depth -> 3D point clouds -> depth (new view) -> normal (new view). You can refer [this repo](https://github.com/YertleTurtleGit/depth-from-normals) for normal2depth and [this repo](https://github.com/cobanov/depth2normal) for depth2normal.

Best,

**Comment by altava-sgp** [comment]
@haodong2000 Thanks for your answer. I will try as you said. 👍

**Comment by altava-sgp** [comment]
@haodong2000 I also hope Lotus can generate various normals like I said.
It will be much helpful for AI generation.
Please consider this seriously. 🙏

**Comment by altava-sgp** [comment]
Like these.
![normals_back_masked](https://github.com/user-attachments/assets/0e409dd9-f0f6-4e40-9118-d1ce593c01c7)
![normals_front_left_masked](https://github.com/user-attachments/assets/749995f5-deca-4fba-b4dc-0cf05cb6c11b)
![normals_front_masked](https://github.com/user-attachments/assets/3e2bc40f-c076-4d39-a97a-fe5189da540f)
![normals_front_right_masked](https://github.com/user-attachments/assets/3332e628-c4c2-427b-b55d-0e2ef2938ec2)
![normals_left_masked](https://github.com/user-attachments/assets/98e6f276-891f-4c2e-9e44-01dc95a8de4c)
![normals_right_masked](https://github.com/user-attachments/assets/9d2d5709-d482-4a84-854e-bf3292de9f00)

**Comment by haodong2000** [comment]
Hi @altava-sgp , thanks for response.

I get your point. Currently, Lotus only supports generating **relative** normal maps only for the current view. That is the way we feed the GTs during training.

If you require normal maps that remain consistent across different views, I recommend leveraging camera extrinsics to transform the normal maps into world coordinates. It's training-free.

I am not sure how precise and consistent you need the normal maps to be or what kind of application you are aiming to build. This simple solution may struggle to achieve perfectly consistent multi-view normal maps. If you require absolute consistency, an alternative approach could be to first reconstruct the 3D model and then generate the normal maps through rendering.

**Comment by altava-sgp** [comment]
@haodong2000 Thank you for your kind answer.
Actually, I am trying to generate a good 3D model from a single image.
I will try other methods, including the suggestions you gave. 😄

**Comment by haodong2000** [comment]
Hi, thanks for response!

Actually I have tried to reconstruct 3D mesh using purely **relative** normal and depth maps, please see Fig. 14 of the paper for more details.

It seems that the performance is good but not in very high-quality.

Thus, I believe that by aligning all views  into same (world) coordinates, the performance will boost significantly.

Best,
