### ISSUE TITLE
Questions about the impact of noise input during fine-tuning

### ISSUE THREAD

**Issue by LuckyOne09** [EnVision-Research/Lotus#2]
First of all, thank you for your impressive paper! Your work has greatly advanced the performance and efficiency of using diffusion for depth estimation.

After carefully reading through your paper, I am curious about the role of the noise input during the training process in single-step diffusion. Specifically, have you tried removing the noise input during the fine-tuning phase to see its impact on the results? I would appreciate it if you could share your insights on this topic.

Thank you in advance for your time and assistance.

**Comment by haodong2000** [comment]
Thanks so much for your notice! 

1. I think the role of noise input is to make uncertainty prediction possible, thus, the output is not merely a sample but a distribution. Please see Fig. 9 for some visualizations.

2. We have report the results after removing the noise input, with is named Lotus-D (discriminative). Please see Tab. 1,2,3. Compared with the original Lotus-G (generative) model with noise input, Lotus-D seems to have slightly better performance, but it can not produce uncertainties.

Best,
Haodong

**Comment by LuckyOne09** [comment]
Thank you very much for your quick response! I apologize for my previous misunderstanding. I thought Lotus-D as keeping the noise input constant only during the inference phase without any special treatment during the training phase.
