### ISSUE TITLE
Why is there such a big difference in the colors of your normal map visualization compared to Omnidata and Metric3D?

### ISSUE THREAD

**Issue by ckh0715** [EnVision-Research/Lotus#20]
I haven't studied monocular vision tasks in detail, but I'm curious why there are differences in monocular normal prediction even though they are all tackling the same task?

**Comment by haodong2000** [comment]
Hi there, thanks so much for your interest!

The difference arises from the RGB sequence and the direction used. Lotus (also DSINE and StableNormal) adopt the opposite direction compared to Omnidata and Metric3D.

Here is the code to transform Omnidata's normal map into Lotus's setting.

```python
import cv2

img = cv2.imread('omnidata_normal.png')

# change the sequence of RGB
b, g, r = cv2.split(img)
b = 255 - b
g = 255 - g
r = 255 - r
img = cv2.merge([b, g, r])

# save the image
cv2.imwrite('omnidata_normal_in_lotus_vis.png', img)
```

![image](https://github.com/user-attachments/assets/b4dc46fa-2a32-4e0e-9c29-d337b35db93d)

Best,
Haodong
