### ISSUE TITLE
Release model on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [EnVision-Research/Lotus#4]
Hello @haodong2000 and team 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered through AK's daily papers: https://huggingface.co/papers/2409.18124. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the model you've pre-trained on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) - I see you already have a draft at - https://huggingface.co/spaces/haodongli/Lotus- we can provide you an A100 grant.

What do you think?

Kind regards,

Niels

**Comment by haodong2000** [comment]
I will do it soon, probably tomorrow, today is a little tired, just after a
8hours flight.

Thanks for your advice!

**Comment by haodong2000** [comment]
Dear Niels,

So excited to hear your A100 grant! Ours demos are now available, and we are using L40 GPU. Here are the links:
1. https://huggingface.co/spaces/haodongli/Lotus_Depth
2. https://huggingface.co/spaces/haodongli/Lotus_Normal

Also, I have applied for the A100 access by sending emails to website@huggingface.co and applied for the GPU Grant by opening discussions on each demo:
1. https://huggingface.co/spaces/haodongli/Lotus_Depth/discussions/4
2. https://huggingface.co/spaces/haodongli/Lotus_Normal/discussions/1

Thanks again for your kind notice and the wonderful GPU Grant! I deeply appreciated it.

Best,

**Comment by greenbrettmichael** [comment]
Thank you for creating these hf spaces! they are currently in an error state. Lotus Normal has a runtime error with bitsandbytes not supporting GPU and Lotus Depth is 404 (probably not publically viewable)

**Comment by haodong2000** [comment]
Thanks for notice, I've fixed them. Both demos should be working now.

Sorry for my carelessness yesterday, and thanks again for your kind GPU Grant!

Best,

![image](https://github.com/user-attachments/assets/668e69fc-1a17-45d2-8d48-e364bbbe5710)

![image](https://github.com/user-attachments/assets/289f93a0-547d-4679-ac9b-6b159e5a1054)

**Comment by NielsRogge** [comment]
Hi @haodong2000 awesome work, thanks for sharing everything on the hub, linking them to the paper! https://huggingface.co/papers/2409.18124 looks awesome now👌

We could give you a grant to support your research, so that you can leverage [ZeroGPU](https://huggingface.co/zero-gpu-explorers). ZeroGPU is a new solution where various demos share the same underlying hardware, and GPUs get dynamically assigned based on demand.

Will ping @merveenoyan regarding this

**Comment by haodong2000** [comment]
Thanks so much for linking to the paper page and the GPU Grant!

Yes, I have already posted the huggingface spaces on the media! Hopefully AK will repost or quote my tweet!

Also please consider group the checkpoints in a [collection](https://huggingface.co/collections) @BlingHe , if convenient.

Thanks,

**Comment by yvrjsharma** [comment]
Thank you for hosting apps on Huggingface Spaces @haodong2000, great work!!
It would be great to also have these Gradio apps available locally in your repository. For example, the DepthCrafter repository includes reproducible code for the Spaces Gradio app and they have linked it in the README along with instructions on how to run it. This improves the project's accessibility and discoverability among the community. 
Gradio demo on Tencent's DepthCrafter repo: https://github.com/Tencent/DepthCrafter?tab=readme-ov-file#-gradio-demo

**Comment by haodong2000** [comment]
Hi Niels,

I have just added the local gradio demo into this repo.

Thanks for your kind reminder and the support from Huggingface community!

Best,

**Comment by yvrjsharma** [comment]
Awesome, thank you so much for moving quickly on this! 🤗

**Comment by NielsRogge** [comment]
Thanks so much for collaborating, I'm going to close this issue, let us know if you have any future releases which we can help with. 🤗
