### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by resurgo97** [EnVision-Research/Lotus#6]
Hi, I have a couple of questions:

1. Do you plan to upload the training code as well? If so, could you share when you might do this?
2. From what I understand, you adopted x₀ prediction instead of ϵ prediction. Does the base model (the one you pretrained) originally use ϵ prediction, and did you switch it to x₀ prediction afterward? If so, did you find that changing the prediction target negatively impacted optimization, given that the model had to learn a different objective?

Thanks in advance for any clarification!

**Comment by haodong2000** [comment]
Hi, thanks so much for your interest!

We do plan to release the training code, but we have to ask our supervisor first.

Please wait for my reply. Thanks.

Best,

**Comment by haodong2000** [comment]
Hi there, thanks again for your interest!

The training code will be released upon the acceptance of our paper. Same as [Marigold](https://github.com/prs-eth/Marigold).

Upon any questions, please feel free to reach out to us :)

**Comment by Cmonsta6** [comment]
Greetings Lotus team,

May I request the training logic for my research?

Thank you and happy new year

**Comment by Cmonsta6** [comment]
Greetings Lotus team, @BlingHe @haodong2000 

May I request the training logic for my research?

Thank you and happy new year
